### ISSUE TITLE
Native lib - Disposable interface

### ISSUE THREAD

**Issue by XakepSDK** [astei/velocity#59]
Java already has `Closeable`/`AutoCloseable` for native resources. Why not use it instead of `Disposable`?

**Comment by astei** [comment]
Because the `Closeable` interface is not appropriate for our situation. It is intended for I/O contexts, and the natives do not use any I/O resources (only allocating and freeing native data structures). Furthermore, they are almost always guaranteed to succeed, and the superfluous exception handling would make the code harder to read.

In particular, I took the example of the `end()` methods from `Deflater` and `Inflater`, which are quite similar to the design adopted for the Velocity natives. Likewise, there is other precedent for a separate "disposable" interface other than `java.io.Closeable`.

Further, it makes no sense to use `AutoCloseable` for Velocity's natives, given that Velocity's native resources are very long-lived compared to the typical `AutoCloseable` resources like `FileInputStream`.
