### ISSUE TITLE
About entity rewrite

### ISSUE THREAD

**Issue by Leymooo** [astei/velocity#7]
I read that you want integrate velocity to paper and sponge. 

How about to make velocity to handle(generate) players entity ids and sync it across network? 

Ex:
1. Paper reserve from 1 to 50000 entity ids.
2. Player join to network and velocity generate a player id. 
2. Velocity send a custom packet or handshake with generated player entity id(from 1 to 50000)
3. Paper send a login(joinGame) packet.
4. Velocity check if sended entity id is generated by velocity and disable entity rewrite, if not enable entity rewrite.

**Comment by kashike** [comment]
Entity rewrite is not necessary in modern versions of Minecraft - this is not necessary.

**Comment by Leymooo** [comment]
But why bungeecord is using entity rewrite?

**Comment by kashike** [comment]
Because BungeeCord is dumb.

**Comment by Leymooo** [comment]
You can not send a login packet twice, because some clients may have bugs or crashes (mods or cheats)

Without entity rewrite can cause a entity id duplication on client (entity and client player entity id)

**Comment by kashike** [comment]
Yes you can - you've been able to send the "join game" packet more than once for a while now.

**Comment by Leymooo** [comment]
Yes, you can send join game twice. but it cause bugs on modded clients. I am tested it and online was lower   by ~20%

**Comment by electronicboy** [comment]
Bungeecord already causes the join game to be sent twice, the only change here is that the proxy wouldn't be rewriting the players entity ID in packets.

**Comment by Leymooo** [comment]
If you want to lose online, its a your chose. There are a lot of players with cheats. And with mods too.

I am already say, that online on my server was dropped by 20% when i try to use a alt-respawn.

**Comment by mikroskeem** [comment]
It's your choice to press the fork button as well.

**Comment by Leymooo** [comment]
I just said to kashike why send login packet twice is bad. 

Also there is commit with begin of entity rewrite, https://github.com/astei/velocity/commit/515248fa99f100a64e0e7f92c9ee60ab6f4c80ad. 

I just write some ideas how to make entity rewrite better, and reduce cpu usage by disabling entity rewrite.

**Comment by electronicboy** [comment]
On the branch which disables entity rewrites, it sends its own login packet, as opposed to passing through original one, so that it can send a login packet and then a respawn packet.

There are several servers which run their own forks of bungee without this entity rewrite logic without any issues, in fact, many modded servers take this approach and run perfectly fine and quite practically have no option other than this in order to run;

Are there going to be teething issues with some mods? Yes, but there is a whole idea here that by providing an environment which attempts to drop a lot of the quirky behavior that bungeecord shoves onto these mods sees a better chance of them actually attempting to provide some level of support for this software, as opposed to the current behavior of mod developers either providing support for it reluctantly, or shoving off support entirely.

**Comment by Leymooo** [comment]
Okey. Now i see, that velocity uses a rewriter/remapper only for 1.8. 

But why you use it only for 1.8 if in 1.8 and 1.12.2 implementation/packet_handle is the same. https://www.diffchecker.com/Vrr01myy
